In [1]:
import numpy as np #Import the leabrary as np shortcut

In [2]:
arry1 = np.array([1,2,3,])
print(array)

[1 2 3]


In [4]:
arry2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(arry2.shape)

(15,)


In [5]:
a = arry2.reshape(3,5) #Reshape the array az 3x5 matrix
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [8]:
print("Shape:",a.shape) #Array shape
print("Dimention:",a.ndim) #Array dimention
print("Datatype:",a.dtype.name) #Array Datatype
print("Size:",a.size) #Array size
print("Type:",type(a)) #Arry type

Shape: (3, 5)
Dimention: 2
Datatype: int32
Size: 15
Type: <class 'numpy.ndarray'>


In [10]:
arry3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #Tow dimantional array
print(arry3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
arry3[0,0] = 13 #Change the firts element
print("New value is:",arry3[0,0])

13


In [14]:
zeros = np.zeros((3,4)) #Array of zeros
ones = np.ones((3,4)) #Array of ones
print(zeros)
print(ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
arry4 = np.arange(10,50,5) #Generate array from 10 to 50 incrising 5
a = np.linspace(0,10,20)

In [17]:
#Math

a = np.array([1,2,3])
b = np.array([1,2,3])

print(a+b)
print(a-b)
print(a*b)
print(a**2)

[2 4 6]
[0 0 0]
[1 4 9]
[1 4 9]


In [23]:
#Lists and numpty arrays

list1 = [1,2,3,4]
arry = np.array([5,6,7,8])

print(list1)
print(arry)

a = np.array([1,2,3])
b=a
c=a

[1, 2, 3, 4]
[5 6 7 8]


In [24]:
b[0] = 5
print(a,b,c)

[5 2 3] [5 2 3] [5 2 3]


In [25]:
a[0] = 5
d = a.copy() # copy the array
print(d)

[5 2 3]


In [33]:
# Print one dimantional arrays

a = np.array([1,2,3,4,5,6,7,8,9,10])

print(a[0]) #Firts 
print(a[0:4]) #
print(a[::-1])

1
[1 2 3 4]
[10  9  8  7  6  5  4  3  2  1]


In [32]:
# Print towe dimantional arrays

b = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(b[1,1])
print(b[1,1:4])
print(b[-1,:])
print(b[:,-1])

7
[7 8 9]
[ 6  7  8  9 10]
[ 5 10]


In [35]:
b = b.ravel() #Convert tow dimantional arrya to one dimantional
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [36]:
b.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])